"""Reports API routes — read-only views over AnalysisTask + DeepInsight data."""

import asyncio
import logging
import os
import shutil
import subprocess
import tempfile

from fastapi import APIRouter, Depends, HTTPException, Query, Response
from sqlalchemy import select, func, desc
from sqlalchemy.ext.asyncio import AsyncSession

from api.deps import get_db
from models.analysis_task import AnalysisTask, AnalysisTaskStatus
from models.deep_insight import DeepInsight
from schemas.report import (
    ReportDetail,
    ReportInsight,
    ReportListResponse,
    ReportSummary,
)

logger = logging.getLogger(__name__)

router = APIRouter()

# ---------------------------------------------------------------------------
# Resolve the repository root directory (two levels up from this file)
# ---------------------------------------------------------------------------
_REPO_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))


# ---------------------------------------------------------------------------
# GitHub Pages publishing helpers
# ---------------------------------------------------------------------------


def _resolve_executable(name: str) -> str:
    """Resolve an executable name to its full absolute path via ``shutil.which``.

    Raises ``RuntimeError`` if the executable cannot be found.
    """
    path = shutil.which(name)
    if path is None:
        raise RuntimeError(
            f"'{name}' executable is not available on this system. "
            f"Install {name} to enable GitHub Pages publishing."
        )
    return path


def _git_run(
    args: list[str],
    *,
    git_path: str,
    cwd: str | None = None,
    check: bool = False,
) -> subprocess.CompletedProcess[str]:
    """Run a git command using the fully-resolved executable path.

    All arguments are trusted internal constants (branch names, flags, etc.).
    """
    cmd = [git_path, *args]
    return subprocess.run(  # noqa: S603
        cmd,
        capture_output=True,
        text=True,
        cwd=cwd,
        check=check,
    )


def _parse_github_org_repo(remote_url: str) -> tuple[str, str]:
    """Extract (org, repo) from a GitHub remote URL.

    Handles both HTTPS and SSH styles:
      - https://github.com/barkain/teletraan.git
      - git@github.com:barkain/teletraan.git
    """
    cleaned = remote_url.strip().replace(".git", "")
    if "github.com" in cleaned:
        # Split on github.com then grab the trailing path
        tail = cleaned.split("github.com")[-1].lstrip(":/")
        parts = tail.split("/")
        if len(parts) >= 2:
            return parts[-2], parts[-1]
    # Fallback
    return "barkain", "teletraan"


def _generate_index_html(report_files: list[str], org: str, repo: str) -> str:
    """Generate a dark-themed index page that lists all published reports."""
    rows = ""
    for fname in report_files:
        task_id = fname.replace(".html", "")
        rows += (
            f'<tr>'
            f'<td style="padding:10px 16px;border-bottom:1px solid #1e293b;">'
            f'<a href="reports/{fname}" style="color:#60a5fa;text-decoration:none;">{task_id}</a>'
            f'</td>'
            f'</tr>\n'
        )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Teletraan Reports</title>
</head>
<body style="margin:0;padding:0;background:#0f172a;color:#e2e8f0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif;">
<div style="max-width:860px;margin:0 auto;padding:32px 20px;">
  <h1 style="margin:0 0 8px 0;font-size:28px;font-weight:700;color:#f8fafc;">Teletraan Reports</h1>
  <p style="color:#94a3b8;font-size:14px;margin:0 0 24px 0;">Published market analysis reports</p>
  <table style="width:100%;border-collapse:collapse;">
    <thead>
      <tr>
        <th style="text-align:left;padding:10px 16px;border-bottom:2px solid #334155;color:#94a3b8;font-size:12px;text-transform:uppercase;">
          Report ID
        </th>
      </tr>
    </thead>
    <tbody>
      {rows if rows else '<tr><td style="padding:20px 16px;color:#64748b;text-align:center;">No reports published yet.</td></tr>'}
    </tbody>
  </table>
  <div style="margin-top:40px;padding-top:20px;border-top:1px solid #1e293b;text-align:center;">
    <p style="margin:0;color:#475569;font-size:13px;">Generated by <strong style="color:#64748b;">Teletraan</strong></p>
  </div>
</div>
</body>
</html>"""


def _do_publish(task_id: str, html_content: str, repo_dir: str) -> str:
    """Synchronous helper that publishes an HTML report to the gh-pages branch.

    Runs inside ``run_in_executor`` so it does not block the event loop.
    Returns the published GitHub Pages URL on success.
    Raises ``RuntimeError`` on failure.
    """
    # Resolve full path to git executable (raises RuntimeError if missing)
    git_path = _resolve_executable("git")

    # Determine remote URL and derive org/repo
    remote_result = _git_run(
        ["remote", "get-url", "origin"],
        git_path=git_path,
        cwd=repo_dir,
    )
    remote_url = remote_result.stdout.strip() if remote_result.returncode == 0 else ""
    org, repo = _parse_github_org_repo(remote_url) if remote_url else ("barkain", "teletraan")

    tmpdir = tempfile.mkdtemp(prefix="teletraan_ghpages_")
    try:
        # Check if gh-pages branch exists on remote
        ls_result = _git_run(
            ["ls-remote", "--heads", "origin", "gh-pages"],
            git_path=git_path,
            cwd=repo_dir,
        )
        gh_pages_exists = "gh-pages" in ls_result.stdout

        work_dir = os.path.join(tmpdir, "ghpages")

        if gh_pages_exists:
            # Clone only the gh-pages branch (shallow)
            clone_result = _git_run(
                [
                    "clone",
                    "--branch", "gh-pages",
                    "--single-branch",
                    "--depth", "1",
                    remote_url,
                    work_dir,
                ],
                git_path=git_path,
            )
            if clone_result.returncode != 0:
                raise RuntimeError(f"Failed to clone gh-pages: {clone_result.stderr}")
        else:
            # Create a new orphan branch
            os.makedirs(work_dir)
            _git_run(["init"], git_path=git_path, cwd=work_dir, check=True)
            _git_run(
                ["checkout", "--orphan", "gh-pages"],
                git_path=git_path,
                cwd=work_dir,
                check=True,
            )
            _git_run(
                ["remote", "add", "origin", remote_url],
                git_path=git_path,
                cwd=work_dir,
                check=True,
            )

        # Configure git identity for the commit
        _git_run(
            ["config", "user.email", "teletraan@automated.report"],
            git_path=git_path,
            cwd=work_dir,
        )
        _git_run(
            ["config", "user.name", "Teletraan Report Publisher"],
            git_path=git_path,
            cwd=work_dir,
        )

        # Write the report HTML
        reports_dir = os.path.join(work_dir, "reports")
        os.makedirs(reports_dir, exist_ok=True)

        report_path = os.path.join(reports_dir, f"{task_id}.html")
        with open(report_path, "w", encoding="utf-8") as fh:
            fh.write(html_content)

        # Build / update the index page that lists all reports
        report_files = sorted(
            [f for f in os.listdir(reports_dir) if f.endswith(".html")],
            reverse=True,
        )
        index_html = _generate_index_html(report_files, org, repo)
        with open(os.path.join(work_dir, "index.html"), "w", encoding="utf-8") as fh:
            fh.write(index_html)

        # Ensure GitHub Pages serves raw HTML (disable Jekyll processing)
        nojekyll_path = os.path.join(work_dir, ".nojekyll")
        if not os.path.exists(nojekyll_path):
            with open(nojekyll_path, "w") as fh:
                pass

        # Stage, commit, and push
        _git_run(["add", "."], git_path=git_path, cwd=work_dir, check=True)

        commit_result = _git_run(
            ["commit", "-m", f"Publish report {task_id}"],
            git_path=git_path,
            cwd=work_dir,
        )
        if commit_result.returncode != 0:
            raise RuntimeError(f"Git commit failed: {commit_result.stderr}")

        push_result = _git_run(
            ["push", "origin", "gh-pages"],
            git_path=git_path,
            cwd=work_dir,
        )
        if push_result.returncode != 0:
            # Retry with force push (e.g. history diverged due to manual edits)
            push_result = _git_run(
                ["push", "--force", "origin", "gh-pages"],
                git_path=git_path,
                cwd=work_dir,
            )
        if push_result.returncode != 0:
            raise RuntimeError(f"Git push failed: {push_result.stderr}")

        # Try to enable GitHub Pages via gh CLI (best-effort, non-fatal)
        gh_path = shutil.which("gh")
        if gh_path is not None:
            try:
                subprocess.run(  # noqa: S603
                    [
                        gh_path, "api",
                        f"repos/{org}/{repo}/pages",
                        "-X", "POST",
                        "-f", 'source={"branch":"gh-pages","path":"/"}',
                    ],
                    capture_output=True,
                    text=True,
                    timeout=15,
                )
            except subprocess.TimeoutExpired:
                pass

        return f"https://{org}.github.io/{repo}/reports/{task_id}.html"

    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)


async def _publish_to_ghpages(task_id: str, html_content: str, repo_dir: str) -> str:
    """Publish HTML report to gh-pages branch (async wrapper)."""
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(None, _do_publish, task_id, html_content, repo_dir)


# ---------------------------------------------------------------------------
# Route handlers
# ---------------------------------------------------------------------------


@router.get("", response_model=ReportListResponse)
async def list_reports(
    db: AsyncSession = Depends(get_db),
    limit: int = Query(default=20, le=100),
    offset: int = Query(default=0),
):
    """List completed analysis reports.

    Returns completed AnalysisTask records as report summaries,
    ordered by started_at descending.
    """
    base_query = select(AnalysisTask).where(
        AnalysisTask.status == AnalysisTaskStatus.COMPLETED.value
    )

    # Count total
    count_query = select(func.count()).select_from(base_query.subquery())
    total = await db.scalar(count_query) or 0

    # Fetch paginated results
    query = (
        base_query
        .order_by(desc(AnalysisTask.started_at))
        .offset(offset)
        .limit(limit)
    )
    result = await db.execute(query)
    tasks = result.scalars().all()

    items = []
    for task in tasks:
        insight_count = len(task.result_insight_ids) if task.result_insight_ids else 0
        items.append(
            ReportSummary(
                id=task.id,
                started_at=task.started_at,
                completed_at=task.completed_at,
                elapsed_seconds=task.elapsed_seconds,
                market_regime=task.market_regime,
                top_sectors=task.top_sectors or [],
                discovery_summary=task.discovery_summary,
                insights_count=insight_count,
                published_url=task.published_url,
            )
        )

    return ReportListResponse(items=items, total=total)


@router.get("/{task_id}", response_model=ReportDetail)
async def get_report(
    task_id: str,
    db: AsyncSession = Depends(get_db),
):
    """Get a full report for a completed analysis task.

    Loads the AnalysisTask and all associated DeepInsight records.
    """
    result = await db.execute(
        select(AnalysisTask).where(AnalysisTask.id == task_id)
    )
    task = result.scalar_one_or_none()
    if not task:
        raise HTTPException(status_code=404, detail="Report not found")

    # Load associated insights
    insights: list[ReportInsight] = []
    if task.result_insight_ids:
        insight_result = await db.execute(
            select(DeepInsight).where(DeepInsight.id.in_(task.result_insight_ids))
        )
        db_insights = insight_result.scalars().all()
        # Maintain original order from result_insight_ids
        insight_map = {i.id: i for i in db_insights}
        for iid in task.result_insight_ids:
            ins = insight_map.get(iid)
            if ins:
                insights.append(
                    ReportInsight(
                        id=ins.id,
                        insight_type=ins.insight_type,
                        action=ins.action,
                        title=ins.title,
                        thesis=ins.thesis,
                        primary_symbol=ins.primary_symbol,
                        related_symbols=ins.related_symbols or [],
                        confidence=ins.confidence,
                        time_horizon=ins.time_horizon,
                        risk_factors=ins.risk_factors or [],
                        entry_zone=ins.entry_zone,
                        target_price=ins.target_price,
                        stop_loss=ins.stop_loss,
                        invalidation_trigger=ins.invalidation_trigger,
                        supporting_evidence=(
                            ins.supporting_evidence[0]
                            if ins.supporting_evidence and len(ins.supporting_evidence) == 1
                            else {"items": ins.supporting_evidence}
                            if ins.supporting_evidence
                            else None
                        ),
                        created_at=ins.created_at,
                    )
                )

    insight_count = len(task.result_insight_ids) if task.result_insight_ids else 0

    return ReportDetail(
        id=task.id,
        started_at=task.started_at,
        completed_at=task.completed_at,
        elapsed_seconds=task.elapsed_seconds,
        market_regime=task.market_regime,
        top_sectors=task.top_sectors or [],
        discovery_summary=task.discovery_summary,
        insights_count=insight_count,
        published_url=task.published_url,
        insights=insights,
        phases_completed=task.phases_completed or [],
    )


@router.get("/{task_id}/html")
async def get_report_html(
    task_id: str,
    db: AsyncSession = Depends(get_db),
):
    """Generate a self-contained HTML report for a completed analysis.

    Returns a professional dark-theme HTML page with all CSS inlined.
    No external dependencies -- fully portable and printable.
    """
    result = await db.execute(
        select(AnalysisTask).where(AnalysisTask.id == task_id)
    )
    task = result.scalar_one_or_none()
    if not task:
        raise HTTPException(status_code=404, detail="Report not found")

    # Load insights
    insights = []
    if task.result_insight_ids:
        insight_result = await db.execute(
            select(DeepInsight).where(DeepInsight.id.in_(task.result_insight_ids))
        )
        db_insights = insight_result.scalars().all()
        insight_map = {i.id: i for i in db_insights}
        for iid in task.result_insight_ids:
            ins = insight_map.get(iid)
            if ins:
                insights.append(ins)

    html = _build_report_html(task, insights)
    return Response(content=html, media_type="text/html")


@router.post("/{task_id}/publish")
async def publish_report(
    task_id: str,
    db: AsyncSession = Depends(get_db),
):
    """Publish a completed analysis report to GitHub Pages.

    Generates a self-contained HTML report and pushes it to the
    ``gh-pages`` branch under ``reports/{task_id}.html``.  An index
    page listing all published reports is maintained automatically.

    Returns the public URL of the published report.
    """
    # 1. Load the task -------------------------------------------------------
    result = await db.execute(
        select(AnalysisTask).where(AnalysisTask.id == task_id)
    )
    task = result.scalar_one_or_none()
    if not task:
        raise HTTPException(status_code=404, detail="Report not found")

    if task.status != AnalysisTaskStatus.COMPLETED.value:
        raise HTTPException(
            status_code=400,
            detail=f"Cannot publish a report with status '{task.status}'. "
            "Only completed reports can be published.",
        )

    # 2. Generate the HTML report (same logic as GET /{task_id}/html) --------
    insights: list[DeepInsight] = []
    if task.result_insight_ids:
        insight_result = await db.execute(
            select(DeepInsight).where(DeepInsight.id.in_(task.result_insight_ids))
        )
        db_insights = insight_result.scalars().all()
        insight_map = {i.id: i for i in db_insights}
        for iid in task.result_insight_ids:
            ins = insight_map.get(iid)
            if ins:
                insights.append(ins)

    html_content = _build_report_html(task, insights)

    # 3. Publish to gh-pages -------------------------------------------------
    try:
        published_url = await _publish_to_ghpages(task_id, html_content, _REPO_DIR)
    except RuntimeError as exc:
        logger.exception("GitHub Pages publish failed for task %s", task_id)
        raise HTTPException(
            status_code=500,
            detail=str(exc),
        ) from exc

    # 4. Persist the published URL on the task -------------------------------
    task.published_url = published_url
    await db.commit()

    logger.info("Published report %s to %s", task_id, published_url)
    return {"published_url": published_url, "task_id": task_id}


# ---------------------------------------------------------------------------
# HTML report builder
# ---------------------------------------------------------------------------

_ACTION_COLORS = {
    "STRONG_BUY": "#22c55e",
    "BUY": "#4ade80",
    "HOLD": "#facc15",
    "SELL": "#f87171",
    "STRONG_SELL": "#ef4444",
    "WATCH": "#60a5fa",
}

_ACTION_LABELS = {
    "STRONG_BUY": "Strong Buy",
    "BUY": "Buy",
    "HOLD": "Hold",
    "SELL": "Sell",
    "STRONG_SELL": "Strong Sell",
    "WATCH": "Watch",
}


def _esc(text: str | None) -> str:
    """Escape HTML entities."""
    if text is None:
        return ""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _format_duration(seconds: float | None) -> str:
    if seconds is None:
        return "N/A"
    m, s = divmod(int(seconds), 60)
    if m > 0:
        return f"{m}m {s}s"
    return f"{s}s"


def _build_insight_card(ins: DeepInsight) -> str:
    action = ins.action or "WATCH"
    color = _ACTION_COLORS.get(action, "#94a3b8")
    label = _ACTION_LABELS.get(action, action)
    confidence_pct = int((ins.confidence or 0) * 100)

    symbols_html = ""
    if ins.primary_symbol:
        symbols_html += (
            f'<span style="background:#334155;padding:2px 8px;border-radius:4px;'
            f'font-weight:600;font-size:14px;">{_esc(ins.primary_symbol)}</span> '
        )
    if ins.related_symbols:
        for sym in ins.related_symbols[:5]:
            symbols_html += (
                f'<span style="background:#1e293b;padding:2px 6px;border-radius:4px;'
                f'font-size:12px;color:#94a3b8;">{_esc(sym)}</span> '
            )

    targets_html = ""
    if ins.entry_zone or ins.target_price or ins.stop_loss:
        targets_html = '<div style="display:flex;gap:16px;margin-top:12px;flex-wrap:wrap;">'
        if ins.entry_zone:
            targets_html += (
                f'<div style="background:#0f172a;padding:6px 12px;border-radius:6px;">'
                f'<div style="font-size:10px;color:#64748b;text-transform:uppercase;">Entry</div>'
                f'<div style="font-size:14px;font-weight:600;">{_esc(ins.entry_zone)}</div></div>'
            )
        if ins.target_price:
            targets_html += (
                f'<div style="background:#0f172a;padding:6px 12px;border-radius:6px;">'
                f'<div style="font-size:10px;color:#64748b;text-transform:uppercase;">Target</div>'
                f'<div style="font-size:14px;font-weight:600;color:#4ade80;">{_esc(ins.target_price)}</div></div>'
            )
        if ins.stop_loss:
            targets_html += (
                f'<div style="background:#0f172a;padding:6px 12px;border-radius:6px;">'
                f'<div style="font-size:10px;color:#64748b;text-transform:uppercase;">Stop Loss</div>'
                f'<div style="font-size:14px;font-weight:600;color:#f87171;">{_esc(ins.stop_loss)}</div></div>'
            )
        targets_html += "</div>"

    risk_html = ""
    if ins.risk_factors:
        risk_items = "".join(
            f'<li style="margin-bottom:4px;">{_esc(r)}</li>' for r in ins.risk_factors[:5]
        )
        risk_html = (
            f'<div style="margin-top:12px;">'
            f'<div style="font-size:11px;color:#64748b;text-transform:uppercase;margin-bottom:4px;">Risk Factors</div>'
            f'<ul style="margin:0;padding-left:18px;color:#94a3b8;font-size:13px;">{risk_items}</ul>'
            f'</div>'
        )

    invalidation_html = ""
    if ins.invalidation_trigger:
        invalidation_html = (
            f'<div style="margin-top:10px;padding:8px 12px;background:#1c1017;border-left:3px solid #ef4444;'
            f'border-radius:0 6px 6px 0;font-size:13px;color:#fca5a5;">'
            f'<strong>Invalidation:</strong> {_esc(ins.invalidation_trigger)}</div>'
        )

    return f"""
    <div style="background:#1e293b;border-radius:12px;padding:20px;margin-bottom:16px;
                border:1px solid #334155;">
      <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:12px;flex-wrap:wrap;gap:8px;">
        <div style="display:flex;align-items:center;gap:10px;flex-wrap:wrap;">
          <span style="background:{color};color:#0f172a;padding:3px 10px;border-radius:6px;
                       font-weight:700;font-size:12px;text-transform:uppercase;">{_esc(label)}</span>
          {symbols_html}
        </div>
        <div style="display:flex;align-items:center;gap:6px;">
          <div style="width:80px;height:6px;background:#0f172a;border-radius:3px;overflow:hidden;">
            <div style="width:{confidence_pct}%;height:100%;background:{color};border-radius:3px;"></div>
          </div>
          <span style="font-size:12px;color:#94a3b8;">{confidence_pct}%</span>
        </div>
      </div>
      <h3 style="margin:0 0 8px 0;font-size:18px;color:#f1f5f9;">{_esc(ins.title)}</h3>
      <p style="margin:0 0 4px 0;color:#cbd5e1;font-size:14px;line-height:1.6;">{_esc(ins.thesis)}</p>
      {f'<div style="margin-top:6px;font-size:12px;color:#64748b;">Horizon: {_esc(ins.time_horizon)}</div>' if ins.time_horizon else ''}
      {targets_html}
      {risk_html}
      {invalidation_html}
    </div>
    """


def _build_report_html(task: AnalysisTask, insights: list[DeepInsight]) -> str:
    # Format dates
    report_date = ""
    if task.completed_at:
        report_date = task.completed_at.strftime("%B %d, %Y at %H:%M UTC")
    elif task.started_at:
        report_date = task.started_at.strftime("%B %d, %Y at %H:%M UTC")

    # Market regime badge
    regime = task.market_regime or "Unknown"
    regime_color = "#60a5fa"
    regime_lower = regime.lower()
    if "bull" in regime_lower or "expansion" in regime_lower or "risk-on" in regime_lower:
        regime_color = "#4ade80"
    elif "bear" in regime_lower or "contraction" in regime_lower or "risk-off" in regime_lower:
        regime_color = "#f87171"
    elif "neutral" in regime_lower or "mixed" in regime_lower or "transitional" in regime_lower:
        regime_color = "#facc15"

    # Sectors
    sectors_html = ""
    if task.top_sectors:
        sector_badges = "".join(
            f'<span style="background:#1e293b;border:1px solid #334155;padding:4px 12px;'
            f'border-radius:20px;font-size:13px;color:#e2e8f0;">{_esc(s)}</span>'
            for s in task.top_sectors
        )
        sectors_html = (
            f'<div style="margin-top:16px;">'
            f'<div style="font-size:11px;color:#64748b;text-transform:uppercase;margin-bottom:8px;">Top Sectors</div>'
            f'<div style="display:flex;flex-wrap:wrap;gap:8px;">{sector_badges}</div></div>'
        )

    # Discovery summary
    summary_html = ""
    if task.discovery_summary:
        summary_html = (
            f'<div style="margin-top:20px;padding:16px 20px;background:#0f172a;border-radius:10px;'
            f'border:1px solid #1e293b;">'
            f'<div style="font-size:11px;color:#64748b;text-transform:uppercase;margin-bottom:8px;">Executive Summary</div>'
            f'<p style="margin:0;color:#cbd5e1;font-size:14px;line-height:1.7;">{_esc(task.discovery_summary)}</p>'
            f'</div>'
        )

    # Insight cards
    cards_html = ""
    if insights:
        cards_html = "".join(_build_insight_card(ins) for ins in insights)
    else:
        cards_html = (
            '<div style="text-align:center;padding:40px;color:#64748b;">No insights generated for this report.</div>'
        )

    # Phases
    phases_html = ""
    if task.phases_completed:
        phase_items = "".join(
            f'<span style="background:#064e3b;color:#6ee7b7;padding:3px 10px;border-radius:6px;'
            f'font-size:12px;">{_esc(p)}</span>'
            for p in task.phases_completed
        )
        phases_html = (
            f'<div style="margin-top:20px;">'
            f'<div style="font-size:11px;color:#64748b;text-transform:uppercase;margin-bottom:8px;">Phases Completed</div>'
            f'<div style="display:flex;flex-wrap:wrap;gap:6px;">{phase_items}</div></div>'
        )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Market Analysis Report — {_esc(report_date)}</title>
</head>
<body style="margin:0;padding:0;background:#0f172a;color:#e2e8f0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif;line-height:1.5;">
<div style="max-width:860px;margin:0 auto;padding:32px 20px;">

  <!-- Header -->
  <div style="margin-bottom:32px;border-bottom:1px solid #1e293b;padding-bottom:24px;">
    <h1 style="margin:0 0 8px 0;font-size:28px;font-weight:700;color:#f8fafc;">Market Analysis Report</h1>
    <div style="display:flex;align-items:center;gap:12px;flex-wrap:wrap;">
      <span style="color:#94a3b8;font-size:14px;">{_esc(report_date)}</span>
      <span style="background:{regime_color}22;color:{regime_color};padding:3px 12px;border-radius:20px;
                   font-size:13px;font-weight:600;border:1px solid {regime_color}44;">{_esc(regime)}</span>
      <span style="color:#64748b;font-size:13px;">{len(insights)} insight{"s" if len(insights) != 1 else ""} &middot; {_format_duration(task.elapsed_seconds)}</span>
    </div>
    {sectors_html}
    {summary_html}
    {phases_html}
  </div>

  <!-- Insights -->
  <div>
    <h2 style="margin:0 0 16px 0;font-size:20px;font-weight:600;color:#f1f5f9;">Insights</h2>
    {cards_html}
  </div>

  <!-- Footer -->
  <div style="margin-top:40px;padding-top:20px;border-top:1px solid #1e293b;text-align:center;">
    <p style="margin:0;color:#475569;font-size:13px;">Generated by <strong style="color:#64748b;">Teletraan</strong></p>
  </div>

</div>
</body>
</html>"""
